### ISSUE TITLE
Kata1

### ISSUE THREAD

**Issue by zayalabs** [FrozenHearth/JavascriptKatas#4]
TypeError: Reduce of empty array with no initial value

Also, try avoiding nested ternary operators.

**Comment by FrozenHearth** [comment]
Fixed.

Link to PR: https://github.com/FrozenHearth/JavascriptKatas/pull/7

**Comment by deepak-singh** [comment]
Test.assertSimilar(openOrSenior([[45, 12],[55,21],[19, -2],[104, 20]]),['Open', 'Senior', 'Open', 'Senior'])
Test.assertSimilar(openOrSenior([[3, 12],[55,1],[91, -2],[54, 23]]),['Open', 'Open', 'Open', 'Open'])
Test.assertSimilar(openOrSenior([[59, 12],[55,-1],[12, -2],[12, 12]]),['Senior', 'Open', 'Open', 'Open'])

Expected: '['Open', 'Senior', 'Open', 'Senior']', instead got: '[]'
Expected: '['Open', 'Open', 'Open', 'Open']', instead got: '[]'
Expected: '['Senior', 'Open', 'Open', 'Open']', instead got: '[]'

**Comment by FrozenHearth** [comment]
Issue fixed.

Link to commit: https://github.com/FrozenHearth/JavascriptKatas/commit/ce8a07751248c8b30e80fc2411c4d8df88653e77
